### PR TITLE
Closes issue #5

### PR DESCRIPTION
**Pull request by Akshatjaiswal5**
1. Nothing happens on hover so removing the purple border is moot.
2. Made the circular animation infinite.
3. Made the animation start when in viewport. Used Intersection observer to append an 'anim' class when in viewport that has the css for animations.

### CODE REVIEW

**Comment by Akshatjaiswal5** [comment]
I am not sure if this pr is linked with the issue or not, please check.

**Comment by Im-Madhur-Gupta** [comment]
@Akshatjaiswal5 I have linked this PR with the issue, I'll check it out and let you know by tomorrow EOD.

**Comment by Akshatjaiswal5** [comment]
Please review these changes sooner than later, I want them for hacktoberfest. Thank you.

**Review by Im-Madhur-Gupta — APPROVED** [review]
LGTM

**Comment by Im-Madhur-Gupta** [comment]
@Akshatjaiswal5 Sorry for the delay, actually I was sick for the past few days. Thanks for contributing.

**Pull request merged**
